services:
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    networks:
      - mynetwork
    # container_name: back
    # ports:
      # - '4000:3000'

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - front
      - back
    networks:
      - mynetwork
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - '80:80'
    stdin_open: true
    networks:
      - mynetwork
    environment:
      - VITE_API_URL=http://backend:3000
    

    
networks:
  mynetwork: